### ISSUE TITLE
Can we add some images to the site like the icons for JS and HTML for the course headings?

### ISSUE THREAD

**Issue by vchrombie** [hiddencodecademy/Courses#26]
The page looks more attractive if we do that. Just add the icons for all the courses just side to that of the course heading. What do you say??

**Comment by PrasadeeJ** [comment]
what do you exactly expect when you say "like the icons for JS and HTML for the course heading"?

**Comment by nicolaihoilund** [comment]
@PrasadeeJ I believe he is referring to small icons next to the card titles.

@vchrombie How will it look more attractive? I split up the courses into sections and I don't think there's confusion on which language the courses are for. It seems unnecessary to me. Feel free to prove me wrong.

**Comment by nicolaihoilund** [comment]
I just took a look at #27 and I understand now. I'm not sure I'm a fan. It messes with the margins and feels out of place. Perhaps if they were smaller and were monochrome ($blue), I would be okay with it.

**Comment by vchrombie** [comment]
Okay, that's fine. We will keep it simple and elegant. :)
